# This is a basic workflow to help you get started with Actions
name: Build and Push to Docker Hub

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          docker build -t vatusa/base:latest images/base
          docker build -t vatusa/nginx:latest images/nginx
          docker build -t vatusa/php:latest images/php
          docker build -t vatusa/php-nginx:latest images/php-nginx 
          docker push vatusa/base:latest 
          docker push vatusa/nginx:latest
          docker push vatusa/php:latest
          docker push vatusa/php-nginx:latest
